name = "d"
entrypoint = "main.d"
extensions = [
  "d"
]
packages = [
  "apt-transport-https"
]
setup = [
  "sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list",
  "sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring",
  "sudo apt-get update && sudo apt-get install dmd-compiler dub",
]


[run]
pty = true
command = [
  "/usr/bin/rdmd",
  "./main.d"
]

[tests]

  [tests.hello]
  code = "void main()\n{    import std.stdio : writeln;\n\n    writeln(\"Hello World!\");\n}"
  output = "Hello World!\n"

